version: '3'

services:
  open-runtimes-node-20.0:
    container_name: open-runtimes-node-20.0
    build:
      context: .
    ports: 
      - 3000:3000
    environment:
      - INTERNAL_RUNTIME_KEY
      - INTERNAL_RUNTIME_ENTRYPOINT
    volumes:
      - ./example/:/usr/code:rw
    command: sh -c "sh /usr/local/src/build.sh && cp /usr/code/code.tar.gz /tmp/code.tar.gz && sh /usr/local/src/start.sh"