version: '3'

services:
  open-runtimes-python-ml-3.12:
    container_name: open-runtimes-python-ml-3.12
    build:
      context: .
    ports: 
      - 3000:3000
    environment:
      - OPEN_RUNTIMES_SECRET
      - OPEN_RUNTIMES_ENTRYPOINT
      - OPEN_RUNTIMES_BUILD_COMMAND
      - OPEN_RUNTIMES_START_COMMAND
    volumes:
      - ./example/:/mnt/code:rw
    command: sh -c "sh helpers/build.sh \"$OPEN_RUNTIMES_BUILD_COMMAND\" && sh helpers/start.sh \"$OPEN_RUNTIMES_START_COMMAND\""